### ISSUE TITLE
Port ABM to nodetimer

### ISSUE THREAD

**Issue by bell07** [Napiophelios/campfire#2]
ABM's produces overhead in engine even no nodes are loaded. Therefore ABM's should not be used if the same functionality can be done by node-timers.

'campfire:campfire' needs to be ported to node-times

**Comment by Napiophelios** [comment]
Yeah, I have thought the same thing for a while,
I just haven't had the time to really mess with minetest for a several months now.
If you want to make a PR that would be appreciated,
but if left up to me, it might be a minute before I ever get to it.

Thanks for the feedback, Bell.
